#!/usr/bin/env bash
# =============================================================================
# configure.sh
# -----------------------------------------------------------------------------
# Reads sensor.conf and renders the Wazuh and Fluent Bit configuration into
# ./generated. Run this whenever you change sensor.conf.
# =============================================================================
set -euo pipefail

cd "$(dirname "$0")"

CONF_FILE="sensor.conf"
EXAMPLE_FILE="sensor.conf.example"

# ---- Ensure a config file exists ----
if [[ ! -f "$CONF_FILE" ]]; then
  if [[ -f "$EXAMPLE_FILE" ]]; then
    cp "$EXAMPLE_FILE" "$CONF_FILE"
    echo "Created $CONF_FILE from $EXAMPLE_FILE."
    echo "Edit $CONF_FILE with your site values, then run ./configure.sh again."
    exit 1
  else
    echo "ERROR: $CONF_FILE not found and no $EXAMPLE_FILE to copy from." >&2
    exit 1
  fi
fi

# ---- Load config (auto-export every variable) ----
set -a
# shellcheck disable=SC1090
source "./$CONF_FILE"
set +a

# ---- Sanity checks ----
require() {
  local name="$1"
  local val="${!name:-}"
  if [[ -z "$val" ]]; then
    echo "ERROR: $name is not set in $CONF_FILE" >&2
    exit 1
  fi
}

for v in CENTRAL_HOST WAZUH_CLUSTER_NAME WAZUH_NODE_NAME WAZUH_NODE_TYPE \
         WAZUH_CLUSTER_KEY WAZUH_CLUSTER_PORT WAZUH_CLUSTER_DISABLED \
         WAZUH_REGISTRATION_PASSWORD LOG_DEST_PORT FLUENT_BIT_FLUSH; do
  require "$v"
done

if [[ "$WAZUH_CLUSTER_KEY" == CHANGE_ME* ]]; then
  echo "ERROR: WAZUH_CLUSTER_KEY still has its placeholder value." >&2
  echo "       Generate one on your master with: openssl rand -hex 16" >&2
  exit 1
fi

# ---- Render ----
command -v envsubst >/dev/null 2>&1 || {
  echo "ERROR: envsubst not found. Install it (Debian/Ubuntu: apt-get install gettext-base)." >&2
  exit 1
}

mkdir -p generated/wazuh generated/fluent-bit

envsubst < config/wazuh/ossec.conf.template          > generated/wazuh/ossec.conf
envsubst < config/fluent-bit/fluent-bit.conf.template > generated/fluent-bit/fluent-bit.conf
cp config/fluent-bit/parsers.conf                       generated/fluent-bit/parsers.conf
cp config/fluent-bit/plugins.conf                       generated/fluent-bit/plugins.conf

# ---- Write the local agent enrollment password for the manager ----
# (Mounted via docker-compose into the manager for authd.)
echo -n "$WAZUH_REGISTRATION_PASSWORD" > generated/wazuh/authd.pass
chmod 600 generated/wazuh/authd.pass

# ---- Generate .env for docker compose interpolation (image tags, ports, TZ) ----
cat > .env <<EOF
# Auto-generated by configure.sh from sensor.conf. Do not edit by hand.
WAZUH_VERSION=${WAZUH_VERSION}
FLUENT_BIT_VERSION=${FLUENT_BIT_VERSION:-3.1}
WAZUH_NODE_NAME=${WAZUH_NODE_NAME}
WAZUH_CLUSTER_NAME=${WAZUH_CLUSTER_NAME}
SENSOR_TIMEZONE=${SENSOR_TIMEZONE}
EOF

echo "Rendered configuration into ./generated"
echo "  - generated/wazuh/ossec.conf"
echo "  - generated/fluent-bit/fluent-bit.conf"
echo "  - generated/fluent-bit/parsers.conf"
echo "  - generated/fluent-bit/plugins.conf"
echo
echo "Next: docker compose up -d"
